### ISSUE TITLE
Too Many Lines Of Code :)

### ISSUE THREAD

**Issue by jonahx** [varocarbas/permutations#1]
Hey varocarbas,

I figured I'd reply here, so as not to clutter up the other thread.  The original version from my post:

```javascript
function nPr(xs, r) {
    if (!r) return [];
    return xs.reduce(function(memo, cur, i) {
        var others  = xs.slice(0,i).concat(xs.slice(i+1)),
            perms   = nPr(others, r-1),
            newElms = !perms.length ? [[cur]] :
                      perms.map(function(perm) { return [cur].concat(perm) });
        return memo.concat(newElms);
    }, []);
}
```

A new version, which handles both repeats and no-repeats, can be achieved simply by changing a single line (the one beginning `var others`):

```javascript
function nPr(xs, r, allowRepeats) {
    if (!r) return [];
    return xs.reduce(function(memo, cur, i) {
        var others  = allowRepeats ? xs.slice(0) : xs.slice(0,i).concat(xs.slice(i+1)),
            perms   = nPr(others, r-1),
            newElms = !perms.length ? [[cur]] :
                      perms.map(function(perm) { return [cur].concat(perm) });
        return memo.concat(newElms);
    }, []);
}
```

I'm hoping that addresses your concern from yesterday and gives you a reason to explore a more functional style.

**Comment by varocarbas** [comment]
As said, my code is even faster than yours. And I can modify it very easily to include/remove any issue. Also it wrote it quite quickly (well... it is certainly a bit complex; I do have experience in this, but also you). Being smaller code doesn't mean anything when doesn't come together with efficiency, clarity and scalability. Anyway... at least anyone (with minimum C knowledge) can understand all what happens in my code :)

**Comment by varocarbas** [comment]
BTW, I think that your repetitions don't work too well. I made a couple of tests and it doesn't deliver what is expected (i.e., number_of_permutations = no_inputs ^ size_permutation), is missing a few ones.

**Comment by jonahx** [comment]
Well, my friend, i don't think I am going sway your mind.  But I will note a couple things: the purpose of my code was readability and maintainability, not efficiency.  I noted that first thing in the post on codereview.  So yes, when speed is really important, it's hard to beat well-tuned procedural C code.  But those cases are rare, especially in the world in web development.  Clarity is usually more important.   Your version is mostly boilerplate and implementation details.  In my version the essence of the algorithm  shines through.

As for the repeats problems, whatever they are, I'm sure they could be fixed.  I just made the change in literally less than 2 minutes, based on what I thought you were looking for, to answer your question about  making changes.  But I think now, we'll have to agree to disagree.  If your approach works for you, keep at it.  Best of luck.

**Comment by varocarbas** [comment]
I wasn't trying to convince you either; just highlighted the advantages of doing things differently. You might be respectful with others' approaches (and motivations to do things in a given way), but there is a whole movement of programmers with "all what is not in a very specific way is wrong" ideas which I don't like at all.

Regarding the repetitions, ironically this is the alternative which I use the most (different approaches...). I meant all the possible combinations, independently upon being repeated or not. If you have n elements combined to form permutations of size k, the total number of these permutations would be: n to the power of k (what your approach doesn't deliver). With loops, this is very easy as far as it is the default behaviour.

Anyway... nice to meet you and I hope that we both have learned something from this experience.

**Comment by jonahx** [comment]
Me too, and honestly I wasn't trying to be disrespectful.   Was just giving my honest opinion.  Other than speed, I don't think a procedural approach has any advantages here.  Btw, I had simply forgotten to pass the `allowRepeats` param to the recursive call.  I believe this does what you want:

```javascript
function nPr(xs, r, allowRepeats) {
    if (!r) return [];
    return xs.reduce(function(memo, cur, i) {
        var others  = allowRepeats ? xs.slice(0) : xs.slice(0,i).concat(xs.slice(i+1)),
            perms   = nPr(others, r-1, allowRepeats),
            newElms = !perms.length ? [[cur]] :
                      perms.map(function(perm) { return [cur].concat(perm) });
        return memo.concat(newElms);
    }, []);
}
```

**Comment by varocarbas** [comment]
Yes, it seems to work now; it was just a small mistake (not even looked at your code). 

I was also giving my opinion: I see lots of advantages in my approach (and for the kind of work I do) and don't want to work with this kind of micro-codes where changes are difficult or even impossible (if I propose modifications involving just certain elements under certain conditions, yours would suffer a serious pain :)). But I do understand that some people like them (and the constrains at their works are different) and I do respect that (= live and let live = you in your world and I in mine, all happy).
